### ISSUE TITLE
can't find window

### ISSUE THREAD

**Issue by staminna** [slymax/webview#2]
Hi
Gradle compiles and the android boots nicely, but I can't find a window or icon to see the app.

Thanks

**Comment by slymax** [comment]
Hi! I'm not sure I understand your issue. Could you explain what you mean with "I can't find a window"? Thanks.

**Comment by staminna** [comment]
I set a URL for the webview then I run the app, android boots but shows nothing but the operative system. Shouldn't there be a icon with the app's webview?

**Comment by slymax** [comment]
yes there should be an icon but I don't think this has anything to do with the webview app. It seems as if Android Studio/your virtual device isn't properly set up. Maybe [this](http://developer.android.com/training/basics/firstapp/running-app.html) will help you.
