### ISSUE TITLE
The App Keeps Crashing 

### ISSUE THREAD

**Issue by Irochi** [slymax/webview#3]
Setting up the app was easy and completely came together beautifully, but, I cannot use app. This is because every time I click on a link the app suddenly crashes. The app pulls up the site and allows me to scroll up and down but I can't click on a link for some odd reason. I thought it was my site but I tested it with others and it still didn't work. Please, if there is anyway to fix this issue please respond. Thank you.

**Comment by slymax** [comment]
Unfortunately, I'm having troubles reproducing your issue. It seems to work fine for me. Are you using a local or a remote source? By "crashing", do you mean that the app freezes or that it closes the app? Thanks.

**Comment by Irochi** [comment]
It closes the entire app, its says "unfortunately, (my app name) has stopped", I don't quite understand the problem, I figured using a source code would be fastee then my manually setting it up, which I'm considering, but, I'm not 100% it will work based on these results. I hope there is a solution to getting the webview to not crash on me when I click on a link.

**Comment by luisriverag** [comment]
I've tested with a few experiments and it works well. Renaming your app is tricky and results in various crashes unless you update all references though. Will try to commit expanded instructions soon

**Comment by slymax** [comment]
yeah I've found that [this](http://stackoverflow.com/a/29092698) is the best way to rename packages in android studio.

**Comment by Irochi** [comment]
I'll repeat the process without renaming anything and see if it works for me. Thanks for replying!
